language: c

rvm:
  - 2.2.3

notifications:
  email: false

dist: xenial
sudo: required

services: docker

stages:
  - tests

jobs:
  include:
    - stage: tests
      script: bash travis/wallaroo-up-example-tester.bash python
      name: "Python Examples"
