baseURL = "https://docs.wallaroolabs.com/"
languageCode = "en-us"
title = "Wallaroo"
theme = "docs-theme"
canonifyurls = false
preserveTaxonomyNames = true

# Do not reformat `wallaroo_version` and `docker_version_url` params
# They are substituted programatically
[params]
wallaroo_version="0.6.1"
docker_version_url="release/wallaroo:0.6.1-c0604d0"
custom_css = ["css/jquery-ui.min.css", "css/jquery-ui.theme.min.css", "css/highlight.css", "css/my.css"]
background_color_class = "bg-green"

[related]
threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[menu]

[[menu.toc]]
name = "Core Concepts"
weight = 1
identifier = "core-concepts"
url = "/core-concepts"

[[menu.toc]]
name = "Installation Guide"
weight = 2
identifier = "ponyinstallation"
url = "/pony-installation"

[[menu.toc]]
name = "Pony Tutorial"
weight = 3
identifier = "ponytutorial"
url = "/pony-tutorial"

[[menu.toc]]
name = "Operators Manual"
weight = 4
identifier = "operators-manual"
url = "/operators-manual"

[[menu.toc]]
name = "Appendix"
weight = 5
identifier = "appendix"
url = "/appendix"

[[menu.main]]
name = "Core Concepts"
url = "/core-concepts/"
weight = 1

[[menu.main]]
name = "Installation"
url = "/pony-installation/"
weight = 10

[[menu.main]]
name = "Tutorial"
url = "/pony-tutorial/"
weight = 20

[[menu.main]]
name = "Operators Manual"
url = "/operators-manual/"
weight = 30
